server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/vivekanumalasetti/L1-SPRINT-CONFIG
          clone-on-start: true
          